name: jerryscd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6420974782668054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b4bfc9'
    - '#043171'
    - '#5088af'
    - '#800080'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.8581634880974889
purpose: []
